name: ScheduledTest

on:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  SeleniumLinux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Test On Linux
      run: mvn clean test -DBrowser=Chrome
